version: '3'
services:
  app:
    image: spygram/python-image:latest
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - 8081:5000
    container_name: python-container
    networks:
      - py-networks
    volumes:
      - /home/sd/mypython-vol:/mypython-vol
networks:
  py-networks:
    driver: bridge
